/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PostLoginRouteImport } from './routes/post-login'
import { Route as PostLogoutRouteImport } from './routes/post-logout'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppWeightRouteImport } from './routes/_app/weight'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PostLoginRoute = PostLoginRouteImport.update({
  id: '/post-login',
  path: '/post-login',
  getParentRoute: () => rootRouteImport,
} as any)
const PostLogoutRoute = PostLogoutRouteImport.update({
  id: '/post-logout',
  path: '/post-logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppWeightRoute = AppWeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/post-login': typeof PostLoginRoute
  '/post-logout': typeof PostLogoutRoute
  '/categories': typeof AppCategoriesRoute
  '/history': typeof AppHistoryRoute
  '/products': typeof AppProductsRoute
  '/weight': typeof AppWeightRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/post-login': typeof PostLoginRoute
  '/post-logout': typeof PostLogoutRoute
  '/categories': typeof AppCategoriesRoute
  '/history': typeof AppHistoryRoute
  '/products': typeof AppProductsRoute
  '/weight': typeof AppWeightRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/post-login': typeof PostLoginRoute
  '/post-logout': typeof PostLogoutRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/weight': typeof AppWeightRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/post-login'
    | '/post-logout'
    | '/categories'
    | '/history'
    | '/products'
    | '/weight'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/post-login'
    | '/post-logout'
    | '/categories'
    | '/history'
    | '/products'
    | '/weight'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/post-login'
    | '/post-logout'
    | '/_app/categories'
    | '/_app/history'
    | '/_app/products'
    | '/_app/weight'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PostLoginRoute: typeof PostLoginRoute
  PostLogoutRoute: typeof PostLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-login': {
      id: '/post-login'
      path: '/post-login'
      fullPath: '/post-login'
      preLoaderRoute: typeof PostLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-logout': {
      id: '/post-logout'
      path: '/post-logout'
      fullPath: '/post-logout'
      preLoaderRoute: typeof PostLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/weight': {
      id: '/_app/weight'
      path: '/weight'
      fullPath: '/weight'
      preLoaderRoute: typeof AppWeightRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppProductsRoute: typeof AppProductsRoute
  AppWeightRoute: typeof AppWeightRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriesRoute: AppCategoriesRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppProductsRoute: AppProductsRoute,
  AppWeightRoute: AppWeightRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PostLoginRoute: PostLoginRoute,
  PostLogoutRoute: PostLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
