FROM mcr.microsoft.com/dotnet/sdk:6.0 AS publish
WORKDIR /app
COPY . .
RUN dotnet publish -c Release -o publish/migrator src/FoodDiary.Migrator/FoodDiary.Migrator.csproj

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=publish app/publish/migrator .
