packageExtensions:
  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  react-dev-utils@*:
    dependencies:
      autoprefixer: "*"
      postcss: "*"
      typescript: "*"
      webpack: "*"
  react-scripts@*:
    dependencies:
      autoprefixer: "*"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
