packageExtensions:
  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  react-dev-utils@*:
    dependencies:
      typescript: "*"
      webpack: "*"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
