approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

npmMinimalAgeGate: 7d

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.16.0.cjs
