name: Deploy

on:
  workflow_dispatch:
      
jobs:
  run-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.100
      - name: Run migrator
        run: dotnet run --configuration Release --project src/backend/src/FoodDiary.Migrator/FoodDiary.Migrator.csproj "${{ secrets.Migrator_DatabaseConnectionString }}"

  deploy:
    runs-on: ubuntu-latest
    needs: run-migrations
    env:
      CR_REGISTRY: ${{ secrets.YC_CR_REGISTRY }}
      CR_REPOSITORY: food-diary
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
  
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
  
      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          container-name: $CR_REPOSITORY
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          public: true
          revision-image-url: cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
          revision-service-account-id: ${{ secrets.YC_REVISION_SERVICE_ACCOUNT_ID }}
          revision-cores: 1
          revision-memory: 512Mb
          revision-core-fraction: 100
          revision-concurrency: 2
          revision-execution-timeout: 10
