name: Deploy

on:
  workflow_dispatch:
      
jobs:
  run-migrations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.100
      - name: Run migrator
        run: dotnet run --configuration Release --project src/backend/src/FoodDiary.Migrator/FoodDiary.Migrator.csproj "${{ secrets.Migrator_DatabaseConnectionString }}"

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: run-migrations

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FOODDIARY_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.FOODDIARY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FOODDIARY_REGISTRY_PASSWORD }}
          containerAppName: food-diary
          resourceGroup: rg-food-diary
          imageToBuild: pkirilin/food-diary:${{ github.sha }}
