name: Trigger auto deployment for food-diary

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ azure-containerapps ]
    paths:
    - '**'
    - '.github/workflows/food-diary-AutoDeployTrigger-3575c3a6-3b6d-4a55-a807-ba83a95222fa.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FOODDIARY_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.FOODDIARY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FOODDIARY_REGISTRY_PASSWORD }}
          containerAppName: food-diary
          resourceGroup: rg-food-diary
          imageToBuild: pkirilin/food-diary:${{ github.sha }}
          
            

     

